### ISSUE TITLE
Test failure on bean-validation example

### ISSUE THREAD

**Issue by leorocha4** [jboss-developer/jboss-eap-quickstarts#1999]
Hi, I executed the instructions correctly and got de following errors:

Failed tests:   
testEmailViolation(org.jboss.as.quickstarts.bean_validation.test.MemberValidationTest): Email was invalid expected:<[not a well-formed email address]> but was:<[Não é um endereço de e-mail]>
  
testPhoneViolation(org.jboss.as.quickstarts.bean_validation.test.MemberValidationTest): Phone number was invalid expected:<[size must be between 10 and] 12> but was:<[tamanho deve estar entre 10 e] 12>

I have not changed any file. Could you help me?

**Comment by sgilda** [comment]
Hi @leorocha4 : Sorry for the delayed response. I am in the process of trying to get someone to help with this issue. I will try to get back to you within the next few days. If you don't here from me, please leave a comment here so I am reminded. :-)

**Comment by sgilda** [comment]
@leorocha4 : I created this JIRA for your issue: https://issues.jboss.org/browse/JBEAP-6232

**Comment by sgilda** [comment]
@leorocha4 : This quickstart should work for you now. The problem was that the Arquillian tests were comparing the English validation warning to the one generated by a different server language. The fix I implemented now compares to English only. If I have time, I will try to add localization at some point.

For now, update your source fies and try this out. It should work now.

**Comment by leorocha4** [comment]
It´s working now!! Thank you so much sgilda.

**Comment by sgilda** [comment]
@leorocha4 : Glad it is working for you. Thanks for letting me know. 
Just be aware that most of the quickstarts are NOT localized, so you may run into similar issues with some of the others as well. :-)
