### ISSUE TITLE
BOM version

### ISSUE THREAD

**Issue by mechevarria** [jboss-developer/jboss-eap-quickstarts#2074]
In building the quickstarts, in the pom.xml, 7.0.0-SNAPSHOT for the version of the jboss-eap-javaee7-with-tools doesn't resolve.

Needs to be updated from SNAPSHOT to GA, or up to the latest patch level of 7.0.7-GA

https://maven.repository.redhat.com/ga/org/jboss/bom/jboss-eap-javaee7-with-tools/

**Comment by brkeh** [comment]
The project won't even build because of this.

Project build error: Non-resolvable import POM: Failure to find org.jboss.bom:jboss-eap-javaee7-with-tools:pom:7.1.0.Beta1 in http://***:8081/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced

**Comment by ctomc** [comment]
@brkeh Artifacts are published and available https://maven.repository.redhat.com/earlyaccess/all/org/jboss/bom/jboss-eap-javaee7-with-tools/7.1.0.Beta1/

Repository for which is defined on parent pom.xml https://github.com/jboss-developer/jboss-eap-quickstarts/blob/7.1.0.Beta/pom.xml#L196 
In your case based on error you see, I would assume you have configured mirror in your settings.xml that forces everything trough it.
In such case, you will need to manually add Red Hat Maven repository to your nexus mirror, so it will be able to load stuff also from this repository.

**Comment by brkeh** [comment]
Yes it was a problem with settings.xml. Thanks very much for the quick reply @ctomc. Unfortunately I didn't see it until now. I'll have to set up notifications.
